name: Release

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install commitizen
    
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Check for changes to release
      id: check_changes
      run: |
        if cz check --rev-range HEAD~1..HEAD; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi
      continue-on-error: true
    
    - name: Bump version and create changelog
      if: steps.check_changes.outputs.has_changes == 'true'
      run: |
        cz bump --yes --changelog
    
    - name: Push changes
      if: steps.check_changes.outputs.has_changes == 'true'
      run: |
        git push
        git push --tags
    
    - name: Get version
      if: steps.check_changes.outputs.has_changes == 'true'
      id: get_version
      run: |
        echo "version=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")" >> $GITHUB_OUTPUT
    
    - name: Create GitHub Release
      if: steps.check_changes.outputs.has_changes == 'true'
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        name: Release v${{ steps.get_version.outputs.version }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false 